const pb = new PocketBase("https://testing.helplink.dev");
const link = document.createElement("link");
link.rel = "icon";
link.type = "image/png";
link.href = "/images/favi.png";

document.head.appendChild(link);
const options = [
    // Engineering
    "Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Electronics Engineering",
    "Electronics and Communication Engineering",
    "Computer Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Aeronautical Engineering",
    "Automobile Engineering",
    "Industrial Engineering",
    "Production Engineering",
    "Materials Engineering",
    "Environmental Engineering",
    "Marine Engineering",
    "Petroleum Engineering",
    "Mining Engineering",
    "Biomedical Engineering",
    "Genetic Engineering",
    "Nanotechnology",
    "Mechatronics",
    "Robotics",
    "Structural Engineering",
    "Software Engineering",
    "Systems Engineering",
    "Thermal Engineering",
    "Nuclear Engineering",

    // Computer Science
    "Computer Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Data Science",
    "Big Data",
    "Cybersecurity",
    "Information Security",
    "Cryptography",
    "Cloud Computing",
    "Quantum Computing",
    "Computer Vision",
    "Natural Language Processing",
    "Human Computer Interaction",
    "Algorithms",
    "Operating Systems",
    "Database Systems",
    "Distributed Systems",
    "Parallel Computing",
    "Computer Graphics",
    "Game Development",
    "Web Development",
    "Mobile Development",
    "Embedded Systems",
    "Blockchain",
    "Internet of Things",
    "Networking",
    "Bioinformatics",
    "Augmented Reality",
    "Virtual Reality",
    "Computational Science",
    "Theoretical Computer Science",

    // Physics
    "Physics",
    "Astrophysics",
    "Astronomy",
    "Cosmology",
    "Quantum Physics",
    "Particle Physics",
    "Theoretical Physics",
    "Experimental Physics",
    "Nuclear Physics",
    "Atomic Physics",
    "Optics",
    "Photonics",
    "Thermodynamics",
    "Classical Mechanics",
    "Electromagnetism",
    "Condensed Matter Physics",
    "Fluid Mechanics",
    "Relativity",
    "Dark Matter",
    "Dark Energy",
    "Plasma Physics",

    // Mathematics
    "Mathematics",
    "Applied Mathematics",
    "Pure Mathematics",
    "Statistics",
    "Probability",
    "Linear Algebra",
    "Calculus",
    "Number Theory",
    "Discrete Mathematics",
    "Topology",
    "Geometry",
    "Differential Equations",
    "Mathematical Modeling",
    "Computational Mathematics",

    // Chemistry
    "Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Analytical Chemistry",
    "Biochemistry",
    "Materials Chemistry",
    "Nanochemistry",

    // Biology
    "Biology",
    "Microbiology",
    "Molecular Biology",
    "Genetics",
    "Biotechnology",
    "Neuroscience",
    "Ecology",
    "Evolutionary Biology",
    "Marine Biology",
    "Botany",
    "Zoology",

    // Earth & Space
    "Earth Science",
    "Geology",
    "Meteorology",
    "Climate Science",
    "Oceanography",
    "Environmental Science",
    "Space Science",
    "Planetary Science",

    // Medicine & Health
    "Medicine",
    "Biomedical Science",
    "Public Health",
    "Medical Technology",
    "Healthcare Technology",
    "Pharmacology",
    "Neuroscience",

    // Social Sciences
    "Psychology",
    "Economics",
    "Political Science",
    "Sociology",
    "Anthropology",
    "Linguistics",
    "Education",
    "International Relations",

    // Business & Finance
    "Finance",
    "Business",
    "Entrepreneurship",
    "Management",
    "Marketing",
    "Accounting",
    "Econometrics",

    // Architecture & Design
    "Architecture",
    "Urban Planning",
    "Industrial Design",
    "Product Design",

    // Interdisciplinary
    "Computational Biology",
    "Computational Physics",
    "Computational Chemistry",
    "Scientific Computing",
    "AI in Healthcare",
    "AI in Education",
    "AI Ethics",
    "Sustainable Technology",
    "Renewable Energy",
    "Green Technology",
    "Smart Cities",
    "Digital Signal Processing",
    "Control Systems",
    "Wireless Communication",
    "Satellite Communication",

    // Aerospace & Aviation
    "Aerospace",
    "Aviation",
    "Rocket Propulsion",
    "Space Exploration",
    "Satellite Engineering",
    "Orbital Mechanics",

    // Emerging Tech
    "Synthetic Biology",
    "Edge Computing",
    "5G Technology",
    "6G Technology",
    "Autonomous Systems",
    "Self Driving Cars",
    "Wearable Technology",
    "Smart Materials",
    "Quantum Mechanics",
    "Quantum Information",
    "Quantum Cryptography",

    // Energy
    "Renewable Energy",
    "Solar Energy",
    "Wind Energy",
    "Hydrogen Energy",
    "Energy Storage",
    "Battery Technology",

    // Misc
    "Ethics in Technology",
    "Science Communication",
    "Research Methodology",
    "Innovation",
    "STEM Education",
    "Music Theory",
    "Literature"
];